
@base = "http://localhost:3000/"


GET  {{base}}
###
GET http://localhost:3000/user
###
GET http://localhost:3000/user/2
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"12",
    "email":"KAHRAMAN89@icloud.com",
    "password":"123456"
}
###
PATCH http://localhost:3000/user/651565e72ea6453a6d6ed27e
Content-Type: application/json

{
    "name":"updatedErçin"
}
###
DELETE http://localhost:3000/user/651565e72ea6453a6d6ed27d
Content-Type: application/json
