
@base = "http://localhost:3000/"


GET  {{base}}
###
GET http://localhost:3000/user
###
GET http://localhost:3000/user/2
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"ercin1",
    "email":"ercin1@gmail.com",
    "password": "ercin1234"
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{   
    "email":"ercin1@gmail.com",
    "password":"ercin123"
}

###
PATCH http://localhost:3000/user/651565e72ea6453a6d6ed276
Content-Type: application/json

{   
    "email":"deneme@gmail.com"
}
###
DELETE http://localhost:3000/user/651565e72ea6453a6d6ed27d
Content-Type: application/json
